<Project Sdk="Microsoft.NET.Sdk">

		<PropertyGroup>
			<OutputType>WinExe</OutputType>
			<TargetFramework>net8.0-windows</TargetFramework>
			<UseWPF>true</UseWPF>
		</PropertyGroup>

  <ItemGroup>
    <Compile Remove="FinanzasPersonales.NET\**" />
    <EmbeddedResource Remove="FinanzasPersonales.NET\**" />
    <None Remove="FinanzasPersonales.NET\**" />
    <Page Remove="FinanzasPersonales.NET\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Views\AhorroView.cs" />
    <Compile Remove="Views\EstadisticaView.cs" />
    <Compile Remove="Views\InversionView.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="Pomelo.EntityFrameworkCore.MySql" Version="9.0.0-preview.2" />
    <PackageReference Include="MySql.Data" Version="9.4.0" />
  </ItemGroup>

</Project>
